# ============================================
# PUT YOUR DATA HERE
# ============================================
s = "ACGCCTATTAGGCAAGGAACGGCGGAACGGAAACGGAACGGGGAACGGTTGTAAAGGAACGGAGGAACGGCCGCGGAACGGGGAACGGAATGGAACGGGGAACGGGCTAGGAACGGCACGGCAGTCCCGGAACGGATAGGGAACGGGGAACGGTGGAACGGACTGGAACGGTAGGAACGGCCATGGAACGGGCGGAACGGTGGAACGGAATGGGAACGGTTATGTGGAACGGGCTCGTTCGTACCCCACGTGGAACGGATGGAACGGGAAGGGAACGGATCCTGGGGAACGGGGAACGGGCACGGAACGGTGGGAACGGTACCTTGGAACGGGCGGAACGGGGGAGGAACGGCGGGGAACGGAGGAACGGTGGAACGGGGAACGGGGGGAACGGATTTGGAACGGCATACCCGGAACGGGTTAAAGGAACGGTTGGGAACGGAACGGCAGGAACGGTGGAACGGCAGGAACGGCGAGGCCATGGAACGGAGCGGAACGGTATCGGGAACGGGGAACGGGAGCCGGGAACGGCAGGAACGGACCGGAACGGGGAACGGGTAGGGAACGGGTCCAGGAACGGTCGGAACGGCCGGAACGGGGGAACGGGGGAACGGGGAACGGGGAACGGGTTAAGGAACGGATTCGGAACGGTGCGAATCGGAACGGAGAGGAACGGGGAACGGGGAACGGGGAACGGAGCCGGGAACGGCGGAACGGGGAACGGGAAGGAACGGGGAACGGTCACGGAACGGGGAACGGATAAAGGAACGGGCTGTGGAACGGTAGGAGGACCGGAACGGGGAACGGCACGGAACGGGGGAGGAACGGATCAGGCGGGAACGGGGAACGGCGGGAACGG"  # DNA string
t = "GGAACGGGG"               # Motif to find

# Alternative: Read from standard input (for Rosalind submission)
# s = input().strip()
# t = input().strip()

# Find all positions where motif t appears in string s
positions = []

# Check each position in s
for i in range(len(s) - len(t) + 1):
    # Extract substring of length equal to motif
    substring = s[i:i+len(t)]
    
    # If it matches the motif, record position (1-indexed)
    if substring == t:
        positions.append(i + 1)  # +1 for 1-indexed positions

# Print all positions separated by spaces
print(' '.join(map(str, positions)))